name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
      - name: Download JUnit
        run: |
          curl -o junit-platform-console-standalone-1.8.2.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
    
      - name: Build and Run Tests
        run: |
          mkdir -p build
          javac -d build src/LoginApp.java src/LoginAppTest.java
          java -cp build org.junit.platform.console.ConsoleLauncher --scan-classpath
